### ISSUE TITLE
Epic Multipart Response

### ISSUE THREAD

**Issue by Raubzeug** [ydb-platform/ydb-embedded-ui#1657]
In this issue we should investigate the possibility to receive multipart response from server and render them incrementally upon receiving next chunk.

- [x] ydb-platform/ydb#11824
- [x] Frontend investigation
- [x] Add multipart [query handler](https://github.com/ydb-platform/ydb/issues/12393)
- [x] #1742
- [x] support multipart responses in query #1837
- [x] Design multipart response https://github.com/ydb-platform/ydb-embedded-ui/issues/1877

https://nda.ya.ru/t/fS1ocFZz7BZwo2

# Development plan

- [x] Investigate performance
- [x] Handle schemes and plans
- [x] check traceId
- [x] Check cancellation by queryId + abort connection
- [x] Multiple results handling
- [x] Handle concurrent_results - multiple results
- [x] Add loading indicator when no data available
- [x] Fix string width adjustment issues
- [x] Add spinner to header
- [x] Correctly handle empty result
- [x] Parse array buffer instead of text
- [x] Implement loading indicators (time, bytes/sec, rows/sec).
- [x] Stop data stream immediately when an error occurs.
- [x] Display error in the standard error area.
- [x] If data is partially loaded, show error above the data.
- [x] Incompleted encoding - not handled for some reason
- [x] Incorrect table resizing on large datasets (like > million)
- [x] Try to use @mjackson/multipart-parser (or some other parsers)
- [x] Design https://github.com/ydb-platform/ydb-embedded-ui/issues/1877 https://github.com/ydb-platform/ydb-embedded-ui/issues/1949
- [x] #1969 https://github.com/gravity-ui/unipika/issues/46
- [x] truncated flag
- [x] Clipboard button https://github.com/gravity-ui/uikit/pull/2112
- [x] Indices column width https://github.com/gravity-ui/react-data-table/issues/45
- [x] Safari request fails https://github.com/ydb-platform/ydb-embedded-ui/issues/1953

**Comment by Raubzeug** [comment]
https://github.com/ydb-platform/ydb/issues/11824
